---
title: "required degree"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Basic Setup
```{r}
library(tidyverse)
library(ggplot2)

source("./vectorizing_strings.R")
Jobs_list <- list.files(path = "./csv files", pattern = "*.csv", full.names = TRUE)
Jobs <- lapply(Jobs_list, read.delim, header = TRUE, sep = ',')

```


## Get the tables about least required degree is whether under university or not

```{r}

degree_level <- c("不拘", "高中以下", "高中", "高中以上", "專科", "專科以上", "大學", "大學以上", "碩士", "碩士以上", "博士")
above_uni <- c("大學", "大學以上", "碩士", "碩士以上", "博士")

J <- Jobs %>% 
  lapply(get_least_degree) %>% 
  lapply(function(x){
    return(data.frame(degree = x) %>% 
      count(degree) %>%
      mutate(total = sum(n)) %>%
      mutate(rate = n / total * 100) %>%
      arrange(factor(degree, levels = degree_level))
    )}) %>%
  lapply(function(x){
    x$degree <- x$degree %>% sapply(function(x){
      return(if (x %in% above_uni) "大學以上" else "大學以下")
    }) %>%
    unname()
    return(x)
  }) %>% # if need all degrees, comment the lapply below(care for the parentheses)
  lapply(function(x){
    return(x %>%
    group_by(degree) %>%
    summarise(n = sum(n), rate = n / total * 100) %>%
    ungroup() %>%
    unique()
  )})

J

```

## Print out the graph

```{r}

font <- "Noto Sans CJK TC"  # if you don't have the font in your computer, you can replace it with any mandarin font in your computer, p.s. the font is HIGHLY RECOMMENDED to have!

plts <- J %>% lapply(function(x){
  return(x %>% ggplot() +
  geom_bar(mapping = aes(x = degree, y = rate), stat = "identity") +
  theme(text = element_text(family = font)) # fix mandarin display issue
  )})
plts

```